<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>BilgisayarliGörmeFinal</RootNamespace>
    <AssemblyName>BilgisayarliGörmeFinal</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
    <StartupObject>BilgisayarliGörmeFinal.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.20110.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

</Project>
